# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-31 05:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_hash', models.CharField(max_length=255, null=True)),
                ('access_token', models.CharField(max_length=255, null=True)),
                ('scope', models.TextField(max_length=255, null=True)),
                ('admin_storeuser_id', models.IntegerField(default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rightway.Store')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bc_id', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('storeusers', models.ManyToManyField(to='rightway.StoreUser')),
            ],
        ),
        migrations.AddField(
            model_name='storeuser',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rightway.User'),
        ),
        migrations.AddField(
            model_name='store',
            name='storeusers',
            field=models.ManyToManyField(to='rightway.StoreUser'),
        ),
    ]
